version: "2"

services:
  server:
    build: .
    environment:
      - TEST_ACCESS_TOKEN=${TEST_ACCESS_TOKEN}
      - TEST_CLIENT_ID=${TEST_CLIENT_ID}
      - TEST_CLIENT_SECRET=${TEST_CLIENT_SECRET}
      - TEST_CODE=${TEST_CODE}
      - TEST_DOMAIN=${TEST_DOMAIN}
    volumes:
      - .:${PROJECT_ROOT}
    working_dir: ${PROJECT_ROOT}
